---
title: An inspiration style guide to American Horror Story
timezone: Europe/Amsterdam
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
    permalink: uploads/:path
defaults:
- scope:
    path: ''
  values:
    image: "/images/meta-icons/android-chrome-512x512.png"
    share:
    - facebook
    - twitter
- scope:
    path: ''
    type: posts
  values:
    layout: post
    has_comments: true
    cover_image: ''
    image: "/images/meta-icons/android-chrome-512x512.png"
short_name: AHS Style
has_comments: true
theme_color: "#fafbfc"
share:
- facebook
- twitter
- tumblr
- pinterest
- reddit
disqus: https-americanhorrorstory-style
description: This site is an inspiration style guide to some of the iconic American
  Horror Story characters. Read about ahs characters and their unique clothing style.
getsimpleform_api_token: cfe536c569efa59f26c3e4966ea452fd
image: "/images/meta-icons/android-chrome-512x512.png"
cover_image: "/uploads/styleguide_logo-41db08.png"
google_analytics: UA-90014538-16
pygments: true
dribbble_username: ahsstyle
facebook_username: 
flickr_username: 
github_username: 
instagram_username: watiseva
linkedin_username: 
pinterest_username: ahsstyleguide
twitter_username: 
youtube_username: 
googleplus_username: 
tumblr_username: nope08
keywords: American Horror Story, Emma Roberts, Sarah Paulson, Taissa Farmiga, Lily
  Rabe, Ryan Murphy, Evan Peters, American Horror Story Coven, American Horror Story
  Apocalypse, American Horror Story season 3, American Horror Story season 8, Billie
  Lourd
rss: true
amoutme_link: https://about.me/ahsstyle
issuucom_link: https://issuu.com/americanhorrorstory.style
theverge_link: https://www.theverge.com/users/americanamericanhorrorstory.style
livejournal_link: https://ahsstyle.livejournal.com/
thinglink_link: https://www.thinglink.com/user/1107984131481927681
goodreads_link: https://www.goodreads.com/user/show/88013758-ahsstyle
lastfm_link: https://www.last.fm/user/ahsstyle
github_link: https://github.com/LesterGallagher/americanhorrorstory
calameo_link: https://www.calameo.com/accounts/5720793
fancy_link: https://fancy.com/ahsstyle
hiivecouk_link: https://www.screenskills.com/profile/7bd7187a-7484-4ce4-96c5-ae57c1d0897c/
itsmyurl_link: https://itsmyurls.com/ahsstyle
8tracks_link: https://8tracks.com/ahsstyle
facebook:
  app_id: 
  publisher: 
  admins: 
webmaster_verifications:
  google: 
  bing: 
  alexa: 
  yandex: 
  baidu: 
twitter:
  username: 
author: Sem Postma
designer: Eva van der Weide
lang: en
humanstxt_author:
  name: Sem Postma
  from: Oosterhout, Noord Brabant, The Netherlands
  role: Developer
  email: sem.postma@gmail.com
humanstxt_designer:
  name: Eva van der Weide
  from: Oosterhout, Noord Brabant, The Netherlands
  role: Designer
  email: ezaa@live.nl
markdown: kramdown
url: https://americanhorrorstory.style
enforce_ssl: americanhorrorstory.style
plugins:
- jekyll-feed
- jekyll-sitemap
- jekyll-seo-tag
sass:
  style: compressed
  sass_dir: _sass
exclude:
- vendor
longdescription: This site is an inspiration style guide to the characters of the
  incredibly popular American Horror Story series. This site contains articles about
  the characters and their clothing style. Each article describes the character's
  clothing style, contains images and also gives you a list of links to clothing items
  that are inspired by the character. This is a great way for people to easily access
  your site and inspire them to browse through your clothing items.
