---
title: An inspiration style guide to American Horror Story
comments: true
share:
  - facebook
  - twitter
  - google
  - tumblr
  - email
  - pinterest
  - linkedin
  - reddit
  - xing
  - whatsapp
  - hackernews
  - vk
  - telegram
disqus: https-americanhorrorstory-style
description: This site is an inspiration style guide to some of the iconic American
  Horror Story characters. On this website you can search for different American Horror
  Story characters and their unique clothing style.
cover_image: "/uploads/styleguide_logo.png"
getsimpleform_api_token: cfe536c569efa59f26c3e4966ea452fd
image_src: "/uploads/styleguide_logo.jpg"
google_analytics: UA-90014538-16
pygments: true
dribbble_username: 
facebook_username: 
flickr_username: 
github_username: 
instagram_username: watiseva
linkedin_username: 
pinterest_username: 
twitter_username: 
youtube_username: 
googleplus_username: 
tumblr_username: nope08
keywords: American Horror Story, Emma Roberts, Sarah Paulson, Taissa Farmiga, Lily
  Rabe, Ryan Murphy, Evan Peters, American Horror Story Coven, American Horror Story
  Apocalypse, American Horror Story season 3, American Horror Story season 8, Billie
  Lourd
rss: true
facebook:
  app_id: 
  publisher: 
  admins: 
webmaster_verifications:
  google: 
  bing: 
  alexa: 
  yandex: 
  baidu: 
twitter:
  username: 
author: Sem Postma
designer: Eva van der Weide
lang: en
humanstxt_author:
  name: Sem Postma
  from: Oosterhout, Noord Brabant, The Netherlands
  role: Developer
  email: sem.postma@gmail.com
humanstxt_designer:
  name: Eva van der Weide
  from: Oosterhout, Noord Brabant, The Netherlands
  role: Designer
  email: ezaa@live.nl
timezone: Europe/Amsterdam
markdown: kramdown
url: https://americanhorrorstory.style
enforce_ssl: americanhorrorstory.style
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
    permalink: uploads/:path
defaults:
- scope:
    path: ''
  values:
    share: 
      - facebook
      - twitter
- scope:
    path: ''
    type: pages
  values:
    layout: page
- scope:
    path: ''
    type: posts
  values:
    layout: post
    comments: true
    cover_image: ''
plugins:
- jekyll-feed
- jekyll-sitemap
- jekyll-seo-tag
sass:
  style: compressed
  sass_dir: _sass
exclude:
- vendor